"""certificados_salud_animal

Revision ID: 12f952acface
Revises: ffe97866c40b
Create Date: 2026-09-16 08:29:51.366013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f952acface'
down_revision = 'ffe97866c40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados_salud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consecutivo', sa.String(length=30), nullable=False),
    sa.Column('token_verificacion', sa.String(length=64), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('finalidad', sa.String(length=50), nullable=False),
    sa.Column('ciudad_origen', sa.String(length=100), nullable=True),
    sa.Column('ciudad_destino', sa.String(length=100), nullable=True),
    sa.Column('pais_destino', sa.String(length=100), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('temperatura_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('dictamen_texto', sa.Text(), nullable=False),
    sa.Column('apto_para_viajar', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('datos_vacunacion', sa.JSON(), nullable=False),
    sa.Column('datos_desparasitacion', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('dias_vigencia', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('hash_integridad_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_medicas.id'], name=op.f('fk_certificados_salud_consulta_id_consultas_medicas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_certificados_salud_mascota_id_mascotas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_certificados_salud_tutor_id_tutores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], name=op.f('fk_certificados_salud_veterinario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificados_salud'))
    )
    with op.batch_alter_table('certificados_salud', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificados_salud_consecutivo'), ['consecutivo'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificados_salud_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificados_salud_mascota_id'), ['mascota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificados_salud_token_verificacion'), ['token_verificacion'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificados_salud_tutor_id'), ['tutor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados_salud', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificados_salud_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_certificados_salud_token_verificacion'))
        batch_op.drop_index(batch_op.f('ix_certificados_salud_mascota_id'))
        batch_op.drop_index(batch_op.f('ix_certificados_salud_estado'))
        batch_op.drop_index(batch_op.f('ix_certificados_salud_consecutivo'))

    op.drop_table('certificados_salud')
    # ### end Alembic commands ###
