"""aprobaciones de precio minimo

Revision ID: 7c855de5f314
Revises: b0c417ddec36
Create Date: 2026-09-14 15:13:35.701905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c855de5f314'
down_revision = 'b0c417ddec36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprobaciones_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=180), nullable=False),
    sa.Column('precio_original', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_solicitado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_aprobado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], name=op.f('fk_aprobaciones_precio_admin_id_usuarios')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_aprobaciones_precio_producto_id_productos')),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], name=op.f('fk_aprobaciones_precio_solicitante_id_usuarios')),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes_producto.id'], name=op.f('fk_aprobaciones_precio_variante_id_variantes_producto')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_aprobaciones_precio_venta_id_ventas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aprobaciones_precio'))
    )
    with op.batch_alter_table('aprobaciones_precio', schema=None) as batch_op:
        batch_op.create_index('ix_aprobaciones_precio_estado', ['estado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprobaciones_precio', schema=None) as batch_op:
        batch_op.drop_index('ix_aprobaciones_precio_estado')

    op.drop_table('aprobaciones_precio')
    # ### end Alembic commands ###
