"""fase 6: historias medicas, vacunas y desparasitaciones

Revision ID: b0c417ddec36
Revises: c5d3e891a203
Create Date: 2026-09-14 14:23:35.045653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c417ddec36'
down_revision = 'c5d3e891a203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desparasitaciones_mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=True),
    sa.Column('producto', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('dosis', sa.String(length=50), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('fecha_proxima', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_desparasitaciones_mascotas_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_desparasitaciones_mascotas_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_desparasitaciones_mascotas_tutor_id_tutores')),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], name=op.f('fk_desparasitaciones_mascotas_veterinario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desparasitaciones_mascotas'))
    )
    with op.batch_alter_table('desparasitaciones_mascotas', schema=None) as batch_op:
        batch_op.create_index('ix_desparasitaciones_mascotas_mascota', ['mascota_id', 'fecha_aplicacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_desparasitaciones_mascotas_mascota_id'), ['mascota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_desparasitaciones_mascotas_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('vacunas_mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=True),
    sa.Column('nombre_vacuna', sa.String(length=120), nullable=False),
    sa.Column('lote', sa.String(length=60), nullable=True),
    sa.Column('laboratorio', sa.String(length=100), nullable=True),
    sa.Column('dosis', sa.String(length=50), nullable=True),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('fecha_proxima', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_vacunas_mascotas_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_vacunas_mascotas_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_vacunas_mascotas_tutor_id_tutores')),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], name=op.f('fk_vacunas_mascotas_veterinario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacunas_mascotas'))
    )
    with op.batch_alter_table('vacunas_mascotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacunas_mascotas_mascota_id'), ['mascota_id'], unique=False)
        batch_op.create_index('ix_vacunas_mascotas_mascota_proxima', ['mascota_id', 'fecha_proxima'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacunas_mascotas_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('consultas_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=255), nullable=False),
    sa.Column('anamnesis', sa.Text(), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperatura_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('tllc_segundos', sa.Integer(), nullable=True),
    sa.Column('mucosas', sa.String(length=50), nullable=True),
    sa.Column('condicion_corporal', sa.String(length=20), nullable=True),
    sa.Column('examen_sistemas', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('plan_tratamiento', sa.Text(), nullable=False),
    sa.Column('receta_medica', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_consultas_medicas_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_consultas_medicas_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_consultas_medicas_tutor_id_tutores')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_consultas_medicas_venta_id_ventas')),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], name=op.f('fk_consultas_medicas_veterinario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultas_medicas'))
    )
    with op.batch_alter_table('consultas_medicas', schema=None) as batch_op:
        batch_op.create_index('ix_consultas_medicas_mascota_fecha', ['mascota_id', 'fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultas_medicas_mascota_id'), ['mascota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultas_medicas_tutor_id'), ['tutor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_medicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_medicas_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_consultas_medicas_mascota_id'))
        batch_op.drop_index('ix_consultas_medicas_mascota_fecha')

    op.drop_table('consultas_medicas')
    with op.batch_alter_table('vacunas_mascotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacunas_mascotas_tutor_id'))
        batch_op.drop_index('ix_vacunas_mascotas_mascota_proxima')
        batch_op.drop_index(batch_op.f('ix_vacunas_mascotas_mascota_id'))

    op.drop_table('vacunas_mascotas')
    with op.batch_alter_table('desparasitaciones_mascotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desparasitaciones_mascotas_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_desparasitaciones_mascotas_mascota_id'))
        batch_op.drop_index('ix_desparasitaciones_mascotas_mascota')

    op.drop_table('desparasitaciones_mascotas')
    # ### end Alembic commands ###
