"""agenda general, hospitalizacion, cirugias, laboratorio, gastos, cartera y enmiendas

Revision ID: b7e862d70a4e
Revises: 7c855de5f314
Create Date: 2026-09-14 15:39:16.688113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e862d70a4e'
down_revision = '7c855de5f314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=60), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_facturas_proveedor_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_facturas_proveedor_proveedor_id_proveedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facturas_proveedor'))
    )
    with op.batch_alter_table('facturas_proveedor', schema=None) as batch_op:
        batch_op.create_index('ix_facturas_proveedor_estado', ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_proveedor_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_gasto', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('comprobante', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_gastos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gastos'))
    )
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_index('ix_gastos_fecha', ['fecha_gasto'], unique=False)

    op.create_table('pagos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_proveedor.id'], name=op.f('fk_pagos_proveedor_factura_id_facturas_proveedor')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_pagos_proveedor_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos_proveedor'))
    )
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_proveedor_factura_id'), ['factura_id'], unique=False)

    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_citas_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_citas_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['profesional_id'], ['usuarios.id'], name=op.f('fk_citas_profesional_id_usuarios')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_citas_tutor_id_tutores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citas'))
    )
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.create_index('ix_citas_estado', ['estado'], unique=False)
        batch_op.create_index('ix_citas_fecha_hora', ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_citas_mascota_id'), ['mascota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citas_profesional_id'), ['profesional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citas_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('cirugias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_procedimiento', sa.String(length=150), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consentimiento_firmado', sa.Boolean(), nullable=False),
    sa.Column('archivo_consentimiento', sa.String(length=255), nullable=True),
    sa.Column('notas_prequirurgicas', sa.Text(), nullable=True),
    sa.Column('protocolo_anestesico', sa.Text(), nullable=True),
    sa.Column('notas_postquirurgicas', sa.Text(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_cirugias_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_cirugias_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_cirugias_tutor_id_tutores')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_cirugias_venta_id_ventas')),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], name=op.f('fk_cirugias_veterinario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cirugias'))
    )
    with op.batch_alter_table('cirugias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cirugias_mascota_id'), ['mascota_id'], unique=False)

    op.create_table('cuentas_tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_cuentas_tutor_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_cuentas_tutor_tutor_id_tutores')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_cuentas_tutor_venta_id_ventas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuentas_tutor'))
    )
    with op.batch_alter_table('cuentas_tutor', schema=None) as batch_op:
        batch_op.create_index('ix_cuentas_tutor_estado', ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_cuentas_tutor_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('hospitalizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_responsable_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_egreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('jaula', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('costo_dia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('fk_hospitalizaciones_creado_por_id_usuarios')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_hospitalizaciones_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_hospitalizaciones_tutor_id_tutores')),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_hospitalizaciones_venta_id_ventas')),
    sa.ForeignKeyConstraint(['veterinario_responsable_id'], ['usuarios.id'], name=op.f('fk_hospitalizaciones_veterinario_responsable_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitalizaciones'))
    )
    with op.batch_alter_table('hospitalizaciones', schema=None) as batch_op:
        batch_op.create_index('ix_hospitalizaciones_estado', ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitalizaciones_mascota_id'), ['mascota_id'], unique=False)

    op.create_table('abonos_cuenta_tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_tutor.id'], name=op.f('fk_abonos_cuenta_tutor_cuenta_id_cuentas_tutor')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_abonos_cuenta_tutor_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abonos_cuenta_tutor'))
    )
    with op.batch_alter_table('abonos_cuenta_tutor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abonos_cuenta_tutor_cuenta_id'), ['cuenta_id'], unique=False)

    op.create_table('enmiendas_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], name=op.f('fk_enmiendas_consulta_autor_id_usuarios')),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_medicas.id'], name=op.f('fk_enmiendas_consulta_consulta_id_consultas_medicas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enmiendas_consulta'))
    )
    with op.batch_alter_table('enmiendas_consulta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enmiendas_consulta_consulta_id'), ['consulta_id'], unique=False)

    op.create_table('evoluciones_hospitalarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospitalizacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('constantes', sa.Text(), nullable=True),
    sa.Column('tratamiento_aplicado', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('alimentacion', sa.String(length=120), nullable=True),
    sa.Column('eliminaciones', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['hospitalizacion_id'], ['hospitalizaciones.id'], name=op.f('fk_evoluciones_hospitalarias_hospitalizacion_id_hospitalizaciones')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_evoluciones_hospitalarias_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evoluciones_hospitalarias'))
    )
    with op.batch_alter_table('evoluciones_hospitalarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evoluciones_hospitalarias_hospitalizacion_id'), ['hospitalizacion_id'], unique=False)

    op.create_table('examenes_laboratorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('solicitado_por_id', sa.Integer(), nullable=True),
    sa.Column('tipo_examen', sa.String(length=150), nullable=False),
    sa.Column('fecha_toma', sa.DateTime(timezone=True), nullable=False),
    sa.Column('laboratorio_externo', sa.String(length=150), nullable=True),
    sa.Column('archivo_resultado', sa.String(length=255), nullable=True),
    sa.Column('interpretacion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_medicas.id'], name=op.f('fk_examenes_laboratorio_consulta_id_consultas_medicas')),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_examenes_laboratorio_mascota_id_mascotas')),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], name=op.f('fk_examenes_laboratorio_solicitado_por_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examenes_laboratorio'))
    )
    with op.batch_alter_table('examenes_laboratorio', schema=None) as batch_op:
        batch_op.create_index('ix_examenes_laboratorio_estado', ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_examenes_laboratorio_mascota_id'), ['mascota_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examenes_laboratorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_examenes_laboratorio_mascota_id'))
        batch_op.drop_index('ix_examenes_laboratorio_estado')

    op.drop_table('examenes_laboratorio')
    with op.batch_alter_table('evoluciones_hospitalarias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evoluciones_hospitalarias_hospitalizacion_id'))

    op.drop_table('evoluciones_hospitalarias')
    with op.batch_alter_table('enmiendas_consulta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enmiendas_consulta_consulta_id'))

    op.drop_table('enmiendas_consulta')
    with op.batch_alter_table('abonos_cuenta_tutor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abonos_cuenta_tutor_cuenta_id'))

    op.drop_table('abonos_cuenta_tutor')
    with op.batch_alter_table('hospitalizaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitalizaciones_mascota_id'))
        batch_op.drop_index('ix_hospitalizaciones_estado')

    op.drop_table('hospitalizaciones')
    with op.batch_alter_table('cuentas_tutor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_tutor_tutor_id'))
        batch_op.drop_index('ix_cuentas_tutor_estado')

    op.drop_table('cuentas_tutor')
    with op.batch_alter_table('cirugias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cirugias_mascota_id'))

    op.drop_table('cirugias')
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citas_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_citas_profesional_id'))
        batch_op.drop_index(batch_op.f('ix_citas_mascota_id'))
        batch_op.drop_index('ix_citas_fecha_hora')
        batch_op.drop_index('ix_citas_estado')

    op.drop_table('citas')
    with op.batch_alter_table('pagos_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_proveedor_factura_id'))

    op.drop_table('pagos_proveedor')
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index('ix_gastos_fecha')

    op.drop_table('gastos')
    with op.batch_alter_table('facturas_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_proveedor_proveedor_id'))
        batch_op.drop_index('ix_facturas_proveedor_estado')

    op.drop_table('facturas_proveedor')
    # ### end Alembic commands ###
