"""agrega fecha_listo a citas_spa

Revision ID: c91779810949
Revises: b7e862d70a4e
Create Date: 2026-09-14 20:25:19.888780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91779810949'
down_revision = 'b7e862d70a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas_spa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_listo', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas_spa', schema=None) as batch_op:
        batch_op.drop_column('fecha_listo')

    # ### end Alembic commands ###
