"""consentimientos_informados_y_firmas

Revision ID: ffe97866c40b
Revises: e8f912c34a5b
Create Date: 2026-09-16 08:16:59.358634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe97866c40b'
down_revision = 'e8f912c34a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_consentimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=255), nullable=True),
    sa.Column('contenido_template', sa.Text(), nullable=False),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plantillas_consentimientos'))
    )
    with op.batch_alter_table('plantillas_consentimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantillas_consentimientos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_plantillas_consentimientos_tipo'), ['tipo'], unique=False)

    op.create_table('consentimientos_emitidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_publico', sa.String(length=64), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('contenido_final', sa.Text(), nullable=False),
    sa.Column('diagnostico_motivo', sa.String(length=255), nullable=True),
    sa.Column('procedimiento_propuesto', sa.String(length=255), nullable=True),
    sa.Column('clasificacion_asa', sa.String(length=10), nullable=True),
    sa.Column('autoriza_rcp', sa.Boolean(), nullable=True),
    sa.Column('destino_cuerpo', sa.String(length=50), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=25), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_medicas.id'], name=op.f('fk_consentimientos_emitidos_consulta_id_consultas_medicas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name=op.f('fk_consentimientos_emitidos_mascota_id_mascotas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_consentimientos.id'], name=op.f('fk_consentimientos_emitidos_plantilla_id_plantillas_consentimientos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id'], name=op.f('fk_consentimientos_emitidos_tutor_id_tutores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['veterinario_id'], ['usuarios.id'], name=op.f('fk_consentimientos_emitidos_veterinario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consentimientos_emitidos'))
    )
    with op.batch_alter_table('consentimientos_emitidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentimientos_emitidos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_consentimientos_emitidos_mascota_id'), ['mascota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consentimientos_emitidos_token_publico'), ['token_publico'], unique=True)
        batch_op.create_index(batch_op.f('ix_consentimientos_emitidos_tutor_id'), ['tutor_id'], unique=False)

    op.create_table('firmas_consentimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consentimiento_id', sa.Integer(), nullable=False),
    sa.Column('nombre_firmante', sa.String(length=150), nullable=False),
    sa.Column('documento_firmante', sa.String(length=30), nullable=False),
    sa.Column('parentesco_o_calidad', sa.String(length=50), nullable=False),
    sa.Column('trazo_firma_png', sa.Text(), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('canal_firma', sa.String(length=30), nullable=False),
    sa.Column('firmado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash_documento_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['consentimiento_id'], ['consentimientos_emitidos.id'], name=op.f('fk_firmas_consentimientos_consentimiento_id_consentimientos_emitidos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firmas_consentimientos')),
    sa.UniqueConstraint('consentimiento_id', name=op.f('uq_firmas_consentimientos_consentimiento_id'))
    )
    with op.batch_alter_table('examenes_laboratorio', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'laboratorio'::character varying"))
        batch_op.create_index('ix_examenes_laboratorio_categoria', ['categoria'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarjeta_profesional', sa.String(length=50), nullable=True))

    # Sembrado de plantillas estándar del sistema
    plantillas_table = sa.table(
        'plantillas_consentimientos',
        sa.column('codigo', sa.String),
        sa.column('tipo', sa.String),
        sa.column('titulo', sa.String),
        sa.column('descripcion_corta', sa.String),
        sa.column('contenido_template', sa.Text),
        sa.column('es_sistema', sa.Boolean),
        sa.column('activo', sa.Boolean),
        sa.column('version', sa.Integer),
        sa.column('creado_en', sa.DateTime(timezone=True)),
        sa.column('actualizado_en', sa.DateTime(timezone=True)),
    )

    from datetime import datetime, timezone
    ahora = datetime.now(timezone.utc)

    op.bulk_insert(
        plantillas_table,
        [
            {
                'codigo': 'EUTANASIA_V1',
                'tipo': 'eutanasia',
                'titulo': 'Consentimiento Informado para Eutanasia Humanitaria',
                'descripcion_corta': 'Autorización para cese indoloro de funciones vitales y disposición de restos',
                'contenido_template': """CONSENTIMIENTO INFORMADO PARA EUTANASIA HUMANITARIA Y DESTINO DE RESTOS

En la ciudad de {{nombre_clinica}}, a las {{fecha_hora}}, yo, {{nombre_tutor}}, identificado(a) con documento de identidad No. {{documento_tutor}}, domiciliado(a) en {{direccion_tutor}}, teléfono {{telefono_tutor}} y correo electrónico {{email_tutor}}, en mi calidad de tutor(a) legal y responsable directo(a) del paciente que responde al nombre de {{nombre_paciente}}:

DATOS DEL PACIENTE:
• Especie: {{especie}} | Raza: {{raza}} | Sexo: {{sexo}} | Edad: {{edad}} | Peso: {{peso}} kg | Microchip: {{id_microchip}}

DECLARO LIBRE, CONSCIENTE Y VOLUNTARIAMENTE:
1. DIAGNÓSTICO Y CONDICIÓN MÉDICA: Que el Médico Veterinario tratante, Dr.(a) {{nombre_veterinario}}, con Tarjeta Profesional No. {{tarjeta_profesional}}, me ha explicado de manera clara, detallada y comprensible el diagnóstico/motivo: "{{diagnostico_motivo}}", evidenciando que mi mascota presenta un cuadro clínico incompatible con una calidad de vida digna, cursando con dolor o sufrimiento no mitigable.

2. AUTORIZACIÓN DEL ACTO MÉDICO: Otorgo mi autorización expresa e irrevocable al equipo médico de {{nombre_clinica}} para realizar el procedimiento de EUTANASIA HUMANITARIA bajo protocolos éticos, mediante sedación profunda previa seguida de sobredosis anestésica para garantizar el cese indoloro de sus funciones vitales.

3. EXONERACIÓN DE RESPONSABILIDAD: Certifico que el paciente no ha mordido a ninguna persona o animal en los últimos 15 días calendario. Exonero plenamente a {{nombre_clinica}} y al equipo veterinario de cualquier responsabilidad legal o patrimonial derivada de este procedimiento.

4. DISPOSICIÓN DEL RESTO DEL CUERPO:
Autorizo la disposición de los restos mortales conforme a la normativa sanitaria y la opción pactada con el centro veterinario.""",
                'es_sistema': True,
                'activo': True,
                'version': 1,
                'creado_en': ahora,
                'actualizado_en': ahora,
            },
            {
                'codigo': 'ANESTESIA_V1',
                'tipo': 'anestesia',
                'titulo': 'Consentimiento Informado para Anestesia y Sedación',
                'descripcion_corta': 'Autorización de sedación, evaluación prequirúrgica y manejo de emergencias',
                'contenido_template': """CONSENTIMIENTO INFORMADO PARA PROCEDIMIENTOS ANESTÉSICOS Y SEDACIÓN

DATOS GENERALES:
• Clínica: {{nombre_clinica}} | Fecha y Hora: {{fecha_hora}}
• Médico Veterinario: Dr.(a) {{nombre_veterinario}} (T.P. {{tarjeta_profesional}})
• Tutor: {{nombre_tutor}} (Doc: {{documento_tutor}}, Tel: {{telefono_tutor}})
• Paciente: {{nombre_paciente}} | Especie: {{especie}} | Raza: {{raza}} | Edad: {{edad}} | Peso: {{peso}} kg

Por medio del presente documento, autorizo la administración de sedación, anestesia regional o anestesia general a mi mascota para la realización de: "{{diagnostico_motivo}}".

CLÁUSULAS INFORMATIVAS Y DE CONSENTIMIENTO:
1. RIESGO INHERENTE: Se me ha informado que todo procedimiento que requiera anestesia o sedación conlleva un riesgo inherente de complicaciones impredecibles (hipotensión, bradicardia, arritmias, shock, reacciones farmacológicas adversas, paro cardiorrespiratorio e incluso la muerte), aun cuando se utilicen los fármacos más seguros y monitorización continua.

2. EXÁMENES PREANESTÉSICOS: Reconozco la importancia crítica de los análisis de laboratorio y cardiológicos previos para mitigar riesgos, los cuales he aportado o autorizado según indicación médica.

3. AYUNO PREVIO: Certifico haber cumplido rigurosamente con el tiempo de ayuno sólido y líquido indicado por el médico veterinario.

4. AUTORIZACIÓN DE EMERGENCIAS: En caso de presentarse una contingencia durante el acto anestésico, autorizo al equipo médico a administrar fármacos de soporte vital y maniobras de estabilización pertinentes.""",
                'es_sistema': True,
                'activo': True,
                'version': 1,
                'creado_en': ahora,
                'actualizado_en': ahora,
            },
            {
                'codigo': 'QUIRURGICO_V1',
                'tipo': 'quirurgico',
                'titulo': 'Consentimiento Informado para Procedimiento Quirúrgico',
                'descripcion_corta': 'Autorización de cirugía, riesgos inherentes y cuidados postoperatorios',
                'contenido_template': """CONSENTIMIENTO INFORMADO PARA ACTO QUIRÚRGICO

En las instalaciones de {{nombre_clinica}}, a las {{fecha_hora}}:
Yo, {{nombre_tutor}}, con documento de identidad {{documento_tutor}}, AUTORIZO la intervención quirúrgica de mi mascota {{nombre_paciente}} (Especie: {{especie}}, Raza: {{raza}}, Sexo: {{sexo}}, Edad: {{edad}}, Peso: {{peso}} kg).

PROCEDIMIENTO QUIRÚRGICO PROGRAMADO:
• Procedimiento: {{diagnostico_motivo}}
• Cirujano Responsable: Dr.(a) {{nombre_veterinario}} | T.P. {{tarjeta_profesional}}

MANIFIESTO Y ACEPTO QUE:
1. INFORMACIÓN RECIBIDA: El cirujano veterinario me ha explicado con claridad la técnica quirúrgica, los objetivos terapéuticos y los pronósticos esperados.

2. RIESGOS Y COMPLICACIONES: Comprendo que toda cirugía conlleva riesgos potenciales tales como hemorragias, infección del sitio quirúrgico, dehiscencia de suturas, seromas o intolerancia a implantes.

3. HALLAZGOS INTRAOPERATORIOS: Autorizo al cirujano a modificar la técnica o extender la intervención si durante el acto quirúrgico se presentan hallazgos o emergencias imprevistas que comprometan la salud del paciente.

4. CUIDADOS POSTOPERATORIOS: Me comprometo a cumplir estrictamente el tratamiento analgésico y antibiótico prescrito, mantener el collar isabelino o body de protección, guardar reposo y acudir a las revisiones y retiro de puntos.""",
                'es_sistema': True,
                'activo': True,
                'version': 1,
                'creado_en': ahora,
                'actualizado_en': ahora,
            },
            {
                'codigo': 'HOSPITALIZACION_V1',
                'tipo': 'hospitalizacion',
                'titulo': 'Consentimiento para Hospitalización y Directiva de RCP',
                'descripcion_corta': 'Admisión hospitalaria, medicación supervisada y directiva de Reanimación Cardiopulmonar',
                'contenido_template': """CONTRATO DE ADMISIÓN Y CONSENTIMIENTO PARA HOSPITALIZACIÓN / CUIDADOS CRÍTICOS

• Centro Veterinario: {{nombre_clinica}} | Fecha de Ingreso: {{fecha_hora}}
• Tutor Responsable: {{nombre_tutor}} | Identificación: {{documento_tutor}} | Tel: {{telefono_tutor}}
• Paciente: {{nombre_paciente}} | Especie: {{especie}} | Raza: {{raza}} | Peso: {{peso}} kg
• Diagnóstico / Motivo de Admisión: {{diagnostico_motivo}}
• Veterinario Tratante: Dr.(a) {{nombre_veterinario}} | T.P. {{tarjeta_profesional}}

TÉRMINOS Y CONDICIONES:
1. PLAN TERAPÉUTICO Y MONITOREO: Autorizo la hospitalización de mi mascota para fluidoterapia intravenosa, fármacos inyectables, toma de muestras diagnósticas, curaciones y monitorización médica continua.

2. EVOLUCIÓN DINÁMICA: Entiendo que los pacientes pueden descompensarse súbitamente a pesar de los cuidados instaurados y que los costos pueden variar de acuerdo a la respuesta médica y requerimiento de insumos o exámenes complementarios.

3. DIRECTIVA ANTICIPADA DE REANIMACIÓN CARDIOPULMONAR (RCP):
En caso de que el paciente presente un Paro Cardiorrespiratorio, manifiesto mi voluntad conforme a lo registrado en este documento (Autoriza RCP / Orden de No Reanimar - DNR).

4. COMUNICACIÓN: Me comprometo a mantener mi línea telefónica {{telefono_tutor}} disponible para decisiones médicas de urgencia.""",
                'es_sistema': True,
                'activo': True,
                'version': 1,
                'creado_en': ahora,
                'actualizado_en': ahora,
            },
            {
                'codigo': 'ALTA_VOLUNTARIA_V1',
                'tipo': 'alta_voluntaria',
                'titulo': 'Acta de Declinación Médica y Alta Voluntaria',
                'descripcion_corta': 'Constancia de rechazo de tratamiento o retiro contra criterio médico profesional',
                'contenido_template': """ACTA DE DECLINACIÓN DE SERVICIOS MÉDICOS / ALTA CONTRA CONSEJO VETERINARIO

• Lugar y Fecha: {{nombre_clinica}}, a las {{fecha_hora}}
• Médico Veterinario: Dr.(a) {{nombre_veterinario}} (T.P. {{tarjeta_profesional}})
• Tutor Responsable: {{nombre_tutor}} | Documento: {{documento_tutor}} | Teléfono: {{telefono_tutor}}
• Paciente: {{nombre_paciente}} | Especie: {{especie}} | Raza: {{raza}} | Edad: {{edad}} | Peso: {{peso}} kg

CONSTANCIA DE DECLINACIÓN EXPRESA:
Por medio de la presente acta, hago constar que he decidido voluntariamente:
• Rechazar la realización de pruebas diagnósticas, hospitalización, cirugía o tratamiento médico recomendado: "{{diagnostico_motivo}}".
• O solicitar el retiro inmediato (Alta Voluntaria) de mi mascota del centro veterinario contra el consejo médico.

ASUNCIÓN TOTAL DE RIESGOS:
1. El Médico Veterinario me ha advertido con claridad los riesgos inminentes de interrumpir la atención médica, incluyendo el agravamiento severo, sufrimiento, secuelas irreversibles o la muerte del paciente {{nombre_paciente}}.

2. Asumo total y plena responsabilidad por las consecuencias médicas o fatales derivadas de mi decisión.

3. Exonero de manera absoluta a {{nombre_clinica}} y a su equipo profesional de cualquier reclamo legal o patrimonial por el desenlace del paciente a partir de la firma de este documento.""",
                'es_sistema': True,
                'activo': True,
                'version': 1,
                'creado_en': ahora,
                'actualizado_en': ahora,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tarjeta_profesional')

    with op.batch_alter_table('examenes_laboratorio', schema=None) as batch_op:
        batch_op.drop_index('ix_examenes_laboratorio_categoria')
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'laboratorio'::character varying"))

    op.drop_table('firmas_consentimientos')
    with op.batch_alter_table('consentimientos_emitidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentimientos_emitidos_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_consentimientos_emitidos_token_publico'))
        batch_op.drop_index(batch_op.f('ix_consentimientos_emitidos_mascota_id'))
        batch_op.drop_index(batch_op.f('ix_consentimientos_emitidos_estado'))

    op.drop_table('consentimientos_emitidos')
    with op.batch_alter_table('plantillas_consentimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantillas_consentimientos_tipo'))
        batch_op.drop_index(batch_op.f('ix_plantillas_consentimientos_codigo'))

    op.drop_table('plantillas_consentimientos')
    # ### end Alembic commands ###
